apiVersion: v1
kind: Secret
metadata:
  name: z-3sp-secrets
type: Opaque
stringData:
  redis-passwd: "CHANGE_ME"
  sms-access-key-id: "CHANGE_ME_ALIYUN_ACCESS_KEY_ID"
  sms-access-key-secret: "CHANGE_ME_ALIYUN_ACCESS_KEY_SECRET"
